const RELIABILITY_EXCERPTS = [
  { id: "EV-001", source: "PERSONAL_CONTINUITY_MANIFEST.md", text: "Every surfaced insight must have evidence. No evidence: DO NOT INFER." },
  { id: "EV-002", source: "TRUST_GOVERNANCE.md", text: "Consent precedes recall." },
  { id: "EV-003", source: "ATTENTION_CONSTITUTION.md", text: "Everything that appears must justify its claim on attention." },
  { id: "EV-004", source: "docs/knowledge/KNOWLEDGE_BASE_FOUNDATION_REVIEW.md", text: "Build only the knowledge structure. No implementation." },
  { id: "EV-005", source: "docs/graph/continuity_graph_schema_v1.md", text: "No evidence -> No graph link. No source -> No continuity object." },
  { id: "EV-006", source: "docs/metrics/metrics_governance_v1.md", text: "Metrics inform. Metrics do not decide." },
  { id: "EV-007", source: "docs/reasoning/continuity_director_charter_v1.md", text: "The Continuity Director does not create memories. The Continuity Director does not create facts. The Continuity Director does not make decisions." },
  { id: "EV-008", source: "docs/reasoning/awareness/awareness_qa_charter_v1.md", text: "Awareness QA exists to determine whether a continuity concern deserves human attention." },
  { id: "EV-009", source: "docs/reasoning/trust/trust_qa_charter_v1.md", text: "Trust QA may block surfacing even when awareness relevance is high." },
  { id: "EV-010", source: "docs/reasoning/task_writer/moon_task_writer_charter_v1.md", text: "The Task Writer translates approved awareness into a user-facing artifact. It does not create new reasoning." },
  { id: "EV-011", source: "docs/today/moon_today_surface_contract_v1.md", text: "Today may display only items that passed prior constitutional review." },
  { id: "EV-012", source: "apps/moon_today_runtime/runtime_overview.md", text: "The runtime accepts an Approved Awareness Artifact and produces a Rendered Today Item." },
  { id: "EV-013", source: "docs/runtime_demo/runtime_demonstration_overview_v1.md", text: "No real data is used yet because the demo is meant to show reasoning shape without ingestion risk." },
  { id: "EV-014", source: "apps/moon_today_experience_prototype/today_experience_overview.md", text: "Moon Today is a morning awareness surface, not a productivity dashboard." },
  { id: "EV-015", source: "docs/evaluation/human/HUMAN_EVALUATION_REPORT_V1.md", text: "If status is NOT_RUN, verdict must be NO_CLAIM." },
  { id: "EV-016", source: "docs/evaluation/human/execution/human_evaluation_results_v1.md", text: "No reviewer data -> NO_CLAIM." },
  { id: "EV-017", source: "docs/decision_memory/decision_memory_manifest_v1.md", text: "Decision Memory exists to reduce Time To Context." },
  { id: "EV-018", source: "docs/decision_memory/time_to_context_benchmark_plan_v1.md", text: "Compare manual repo reading vs Decision Memory answers." },
  { id: "EV-019", source: "docs/decision_memory/query_proof/decision_query_answer_set_v1.md", text: "Answers must cite decision records." },
  { id: "EV-020", source: "docs/decision_memory/time_to_context_evidence/evidence_source_notes_v1.md", text: "Do not claim independent reviewers unless known." },
  { id: "EV-021", source: "docs/decision_memory/time_to_context_results/benchmark_limitations_v1.md", text: "Claim only early TTC signal." },
  { id: "EV-022", source: "docs/decision_memory/coverage/decision_coverage_map_v1.md", text: "No coverage percentage is calculated." },
  { id: "EV-023", source: "docs/deployment/MOON_TODAY_PROTOTYPE_DEPLOY_REVIEW.md", text: "Public prototype URL opens the prototype." },
  { id: "EV-024", source: "docs/deployment/MOON_RUNTIME_DEMONSTRATION_DEPLOY_REVIEW.md", text: "5 demo cases visible: yes." },
  { id: "EV-025", source: "docs/deployment/MOON_TTC_LAB_DEPLOY_REVIEW.md", text: "Manual Mode works: yes." },
  { id: "EV-026", source: "docs/decision_memory/time_to_context_results/time_reduction_analysis_v1.md", text: "Memory average time: 99.4 seconds." },
  { id: "EV-027", source: "docs/decision_memory/time_to_context_results/confidence_analysis_v1.md", text: "Memory average confidence: 2.9." },
  { id: "EV-028", source: "docs/validation/execution/benchmark_score_summary_v1.md", text: "Total scenarios: 20." },
  { id: "EV-029", source: "docs/decision_memory/coverage/decision_inventory_v1.md", text: "C-030 Deploy TTC Lab publicly." },
  { id: "EV-030", source: "docs/decision_memory/coverage/decision_record_backlog_v1.md", text: "Priority 1: Create a dedicated decision record for TTC Lab measurement UI." },
  { id: "EV-031", source: "docs/evaluation/human/campaign/review_session_log_v1.md", text: "response received: no" },
  { id: "EV-032", source: "apps/moon_today_experience_prototype/feedback.html", text: "Would you want to see this in the morning?" },
  { id: "EV-033", source: "apps/moon_ttc_lab/README.md", text: "No backend. No automatic submission." },
  { id: "EV-034", source: "apps/moon_ttc_lab/ttc_questions.js", text: "Why did Moon delay data ingestion?" },
  { id: "EV-035", source: "docs/decision_memory/decision_entity_schema_v1.md", text: "No decision may be recorded without source evidence." },
  { id: "EV-036", source: "docs/decision_memory/decision_query_spec_v1.md", text: "Decision Memory answers must expose evidence links." },
  { id: "EV-037", source: "docs/decision_memory/DECISION_MEMORY_MVP_REVIEW.md", text: "Verdict: PASS" },
  { id: "EV-038", source: "docs/runtime_demo/runtime_demo_case_mapping_v1.md", text: "Forgotten Commitment -> Graph State -> Metrics -> Authority Outputs -> Today Artifact." },
  { id: "EV-039", source: "docs/validation/audit/expected_actual_independence_check.md", text: "If Trust QA outcome is asserted without consent analysis: NOT_CREDIBLE." },
  { id: "EV-040", source: "docs/validation/audit/CONSTITUTIONAL_AUDIT_REVIEW.md", text: "Today MVP blocked if benchmark credibility is not sufficient." },
  { id: "EV-041", source: "docs/evaluation/human/campaign/experience_redesign_notes_v1.md", text: "Shift from artifact gallery to personal continuity experience." },
  { id: "EV-042", source: "docs/runtime_demo/runtime_demo_review_v1.md", text: "synthetic labels visible: yes" },
  { id: "EV-043", source: "docs/decision_memory/time_to_context_evidence/imported_results_table_v1.md", text: "duplicate_or_malformed: yes" },
  { id: "EV-044", source: "docs/decision_memory/time_to_context_evidence/TTC_RAW_EVIDENCE_IMPORT_REVIEW.md", text: "Treat pasted logs as raw evidence." },
  { id: "EV-045", source: "docs/decision_memory/time_to_context_results/economic_value_signal_v1.md", text: "This is not market proof." },
  { id: "EV-046", source: "docs/decision_memory/coverage/DECISION_MEMORY_COVERAGE_REVIEW.md", text: "Coverage is scoped to known candidate decisions from cataloged sources." },
  { id: "EV-047", source: "docs/knowledge/project_lifecycle.md", text: "Hidden abandonment is a risk." },
  { id: "EV-048", source: "docs/graph/graph_confidence_model.md", text: "Every derived object must expose confidence." },
  { id: "EV-049", source: "docs/metrics/project_metrics.md", text: "Momentum Score is a future metric candidate." },
  { id: "EV-050", source: "docs/reasoning/continuity_concern_classification.md", text: "Goal Drift is a concern type." }
];
